version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: critomonedas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: criptomonedas
      MYSQL_USER: cripto_admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
